spring.application.name=carpooling

# MongoDB
spring.mongodb.uri=mongodb://localhost:27017/carpoolingdb1
spring.mongodb.database=carpoolingdb1

# Server
server.port=8080

# Geocoding API
geocoding.api.key=46a784afbe0741b1bbe86f05f26abe15
app.frontend-url=http://localhost:5173
