spring.application.name=carpooling

# MongoDB
spring.mongodb.uri=mongodb://localhost:27017/carpoolingdb1
spring.mongodb.database=carpoolingdb1

# Server
server.port=8080

# Geocoding API
geocoding.api.key=46a784afbe0741b1bbe86f05f26abe15
app.frontend-url=http://localhost:5173

# JWT Configuration
jwt.secret=a81o0x-OjSlSeF816WXoWvK9Fq3fLulWptFxZGBWOoUieNE3VB_OBi_aEuGFD_JehtDXLukC_QEFxMkpXCnDHQ
jwt.expiration=86400000

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hydies1317@gmail.com
spring.mail.password=eavi ymsc mlwk fdev
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
